spring.application.name=Perfume_e-commerce
spring.data.mongodb.uri=mongodb+srv://louchumdararith02_db_user:xgATfRotfVSjkSMZ@cluster0.b0gbdms.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=perfume

spring.app.jwtSecret=VGhpcyBpcyBteSBTZWN1cmUgS2V5IGZvciBKV1QgLSBDaGFuZ2UgTWUgTGF0ZXIhMTIzNDU2Nzg5MA==
spring.app.jwtExpiration=86400000