spring.application.name=Perfume_e-commerce
spring.data.mongodb.uri=mongodb://Dararith:Thefuck%40reyout%40lkingab0ut@100.66.138.23:27017/?authSource=admin&maxIdleTimeMS=60000&connectTimeoutMS=10000&socketTimeoutMS=10000
spring.data.mongodb.database=perfume

spring.app.jwtSecret=VGhpcyBpcyBteSBTZWN1cmUgS2V5IGZvciBKV1QgLSBDaGFuZ2UgTWUgTGF0ZXIhMTIzNDU2Nzg5MA==
spring.app.jwtExpiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=louchumdararith02@gmail.com
spring.mail.password=edmv csdx ptym yohn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stripe Settings
stripe.secret.key=sk_test_51SoneG2eivwxti7ZpxgiZ5JD3Lhn1w0lpzpods0ESXAx3qc9PAfrhP4DfC1tldtX0Tz4carVWdqzLeMJ4fKZl7HI00y3VYOqeb
stripe.currency=usd

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB