spring.application.name=Perfume_e-commerce
spring.data.mongodb.uri=mongodb+srv://louchumdararith02_db_user:xgATfRotfVSjkSMZ@cluster0.b0gbdms.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=perfume

spring.app.jwtSecret=VGhpcyBpcyBteSBTZWN1cmUgS2V5IGZvciBKV1QgLSBDaGFuZ2UgTWUgTGF0ZXIhMTIzNDU2Nzg5MA==
spring.app.jwtExpiration=86400000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=louchumdararith02@gmail.com
spring.mail.password=edmv csdx ptym yohn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SQLite config
spring.datasource.url=jdbc:sqlite:perfume.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
